apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: wonderful-mongodb
    app.kubernetes.io/instance: all
    app.kubernetes.io/version: 3.4.7
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: wonderful-cinema
    app.kubernetes.io/managed-by: kubectl
  name: wonderful-mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/name: wonderful-mongodb
