apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: wonderful-cinema-catalog
    app.kubernetes.io/instance: all
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: back
    app.kubernetes.io/part-of: wonderful-cinema
    app.kubernetes.io/managed-by: kubectl
  name: wonderful-cinema-catalog
spec:
  ports:
    - name: cinema-catalog
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: wonderful-cinema-catalog
