apiVersion: v1
kind: ConfigMap
metadata:
  name: env-wonderful-booking
  namespace: staging
data:
  PORT: '3000'
  DB: booking
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certs-wonderful-booking
  namespace: staging
data:
  server.crt: |-
    -----BEGIN CERTIFICATE-----
    
    -----END CERTIFICATE-----
  server.key: |-
    -----BEGIN PRIVATE KEY-----
    
    -----END PRIVATE KEY-----
